#!/usr/bin/php -q
<?php
/**
 *  File for the DateHelperTest class
 *
 * (PHP 5)
 *
 * @package PHPonTraxTest
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 * @copyright (c) Walter O. Haas 2006
 * @version $Id$
 * @author Walt Haas <haas@xmission.com>
 */

echo "testing DateHelper\n";

// Call DateHelperTest::main() if this source file is executed directly.
if (!defined("PHPUnit2_MAIN_METHOD")) {
    define("PHPUnit2_MAIN_METHOD", "DateHelperTest::main");
}

require_once "PHPUnit2/Framework/TestCase.php";
require_once "PHPUnit2/Framework/TestSuite.php";

// You may remove the following line when all tests have been implemented.
require_once "PHPUnit2/Framework/IncompleteTestError.php";

require_once "../vendor/trax/trax_exceptions.php";

/**
 * Test class for DateHelper.
 * Generated by PHPUnit2_Util_Skeleton on 2006-03-01 at 13:17:32.
 */
class DateHelperTest extends PHPUnit2_Framework_TestCase {
    /**
     * Runs the test methods of this class.
     *
     * @access public
     * @static
     */
    public static function main() {
        require_once "PHPUnit2/TextUI/TestRunner.php";

        $suite  = new PHPUnit2_Framework_TestSuite("DateHelperTest");
        $result = PHPUnit2_TextUI_TestRunner::run($suite);
    }

    /**
     * Sets up the fixture, for example, open a network connection.
     * This method is called before a test is executed.
     *
     * @access protected
     */
    protected function setUp() {
    }

    /**
     * Tears down the fixture, for example, close a network connection.
     * This method is called after a test is executed.
     *
     * @access protected
     */
    protected function tearDown() {
    }

	/**
	 *  @todo Implement testConstruct()
	 */
    public function testConstruct() {
        // Remove the following line when you implement this test.
        throw new PHPUnit2_Framework_IncompleteTestError;
	}

	/**
	 *  @todo Implement testExpiration_date_select()
	 */
    public function testExpiration_date_select() {
        // Remove the following line when you implement this test.
        throw new PHPUnit2_Framework_IncompleteTestError;
	}

	/**
	 *  @todo Implement testDatetime_select_method()
	 */
    public function testDatetime_select_method() {
        // Remove the following line when you implement this test.
        throw new PHPUnit2_Framework_IncompleteTestError;
	}

	/**
	 *  @todo Implement testDatetime_select_function()
	 */
    public function testDatetime_select_function() {
        // Remove the following line when you implement this test.
        throw new PHPUnit2_Framework_IncompleteTestError;
	}

	/**
	 *  @todo Implement testDate_select_method()
	 */
    public function testDate_select_method() {
        // Remove the following line when you implement this test.
        throw new PHPUnit2_Framework_IncompleteTestError;
	}

	/**
	 *  @todo Implement testDate_select_function()
	 */
    public function testDate_select_function() {
        // Remove the following line when you implement this test.
        throw new PHPUnit2_Framework_IncompleteTestError;
	}

	/**
	 *  @todo Implement testSelect_expiration_date_method()
	 */
    public function testSelect_expiration_date_method() {
        // Remove the following line when you implement this test.
        throw new PHPUnit2_Framework_IncompleteTestError;
	}

	/**
	 *  @todo Implement testSelect_expiration_date_function()
	 */
    public function testSelect_expiration_date_function() {
        // Remove the following line when you implement this test.
        throw new PHPUnit2_Framework_IncompleteTestError;
	}

	/**
	 *  @todo Implement testSelect_date_method()
	 */
    public function testSelect_date_method() {
        // Remove the following line when you implement this test.
        throw new PHPUnit2_Framework_IncompleteTestError;
	}

	/**
	 *  @todo Implement testSelect_date_function()
	 */
    public function testSelect_date_function() {
        // Remove the following line when you implement this test.
        throw new PHPUnit2_Framework_IncompleteTestError;
	}

	/**
	 *  @todo Implement testSelect_datetime_method()
	 */
    public function testSelect_datetime_method() {
        // Remove the following line when you implement this test.
        throw new PHPUnit2_Framework_IncompleteTestError;
	}

	/**
	 *  @todo Implement testSelect_datetime_function()
	 */
    public function testSelect_datetime_function() {
        // Remove the following line when you implement this test.
        throw new PHPUnit2_Framework_IncompleteTestError;
	}

	/**
	 *  @todo Implement testSelect_time()
	 */
    public function testSelect_time() {
        // Remove the following line when you implement this test.
        throw new PHPUnit2_Framework_IncompleteTestError;
	}

	/**
	 *  @todo Implement testSelect_second()
	 */
    public function testSelect_second() {
        // Remove the following line when you implement this test.
        throw new PHPUnit2_Framework_IncompleteTestError;
	}

	/**
	 *  @todo Implement testSelect_minute()
	 */
    public function testSelect_minute() {
        // Remove the following line when you implement this test.
        throw new PHPUnit2_Framework_IncompleteTestError;
	}

	/**
	 *  @todo Implement testSelect_hour()
	 */
    public function testSelect_hour() {
        // Remove the following line when you implement this test.
        throw new PHPUnit2_Framework_IncompleteTestError;
	}

	/**
	 *  @todo Implement testSelect_day_method()
	 */
    public function testSelect_day_method() {
        // Remove the following line when you implement this test.
        throw new PHPUnit2_Framework_IncompleteTestError;
	}

	/**
	 *  @todo Implement testSelect_day_function()
	 */
    public function testSelect_day_function() {
        // Remove the following line when you implement this test.
        throw new PHPUnit2_Framework_IncompleteTestError;
	}

	/**
	 *  @todo Implement testSelect_month_method()
	 */
    public function testSelect_month_method() {
        // Remove the following line when you implement this test.
        throw new PHPUnit2_Framework_IncompleteTestError;
	}

	/**
	 *  @todo Implement testSelect_month_function()
	 */
    public function testSelect_month_function() {
        // Remove the following line when you implement this test.
        throw new PHPUnit2_Framework_IncompleteTestError;
	}

	/**
	 *  @todo Implement testSelect_year_method()
	 */
    public function testSelect_year_method() {
        // Remove the following line when you implement this test.
        throw new PHPUnit2_Framework_IncompleteTestError;
	}

	/**
	 *  @todo Implement testSelect_year_function()
	 */
    public function testSelect_year_function() {
        // Remove the following line when you implement this test.
        throw new PHPUnit2_Framework_IncompleteTestError;
	}

	/**
	 *  @todo Implement testTo_date_select_tag()
	 */
    public function testTo_date_select_tag() {
        // Remove the following line when you implement this test.
        throw new PHPUnit2_Framework_IncompleteTestError;
	}

	/**
	 *  @todo Implement testTo_datetime_select_tag()
	 */
    public function testTo_datetime_select_tag() {
        // Remove the following line when you implement this test.
        throw new PHPUnit2_Framework_IncompleteTestError;
	}

	/**
	 *  @todo Implement testTo_expiration_date_select_tag_method()
	 */
    public function testTo_expiration_date_select_tag_method() {
        // Remove the following line when you implement this test.
        throw new PHPUnit2_Framework_IncompleteTestError;
	}

	/**
	 *  @todo Implement testTo_expiration_date_select_tag_function()
	 */
    public function testTo_expiration_date_select_tag_function() {
        // Remove the following line when you implement this test.
        throw new PHPUnit2_Framework_IncompleteTestError;
	}

}

// Call DateHelperTest::main() if this source file is executed directly.
if (PHPUnit2_MAIN_METHOD == "DateHelperTest::main") {
    DateHelperTest::main();
}

// -- set Emacs parameters --
// Local variables:
// tab-width: 4
// c-basic-offset: 4
// c-hanging-comment-ender-p: nil
// indent-tabs-mode: nil
// End:
?>
