<?php
/**
 *  File for the DateHelperTest class
 *
 * (PHP 5)
 *
 * @package PHPonTraxTest
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 * @copyright (c) Walter O. Haas 2006
 * @version $Id$
 * @author Walt Haas <haas@xmission.com>
 */

echo "testing DateHelper\n";
require_once 'testenv.php';

// Call DateHelperTest::main() if this source file is executed directly.
if (!defined("PHPUnit2_MAIN_METHOD")) {
    define("PHPUnit2_MAIN_METHOD", "DateHelperTest::main");
}

require_once "PHPUnit2/Framework/TestCase.php";
require_once "PHPUnit2/Framework/TestSuite.php";

// You may remove the following line when all tests have been implemented.
require_once "PHPUnit2/Framework/IncompleteTestError.php";

require_once "trax_exceptions.php";
require_once "action_view/helpers.php";
require_once "action_view/helpers/date_helper.php";

/**
 * Test class for DateHelper.
 * Generated by PHPUnit2_Util_Skeleton on 2006-03-01 at 13:17:32.
 */
class DateHelperTest extends PHPUnit2_Framework_TestCase {
    /**
     * Runs the test methods of this class.
     *
     * @access public
     * @static
     */
    public static function main() {
        require_once "PHPUnit2/TextUI/TestRunner.php";

        $suite  = new PHPUnit2_Framework_TestSuite("DateHelperTest");
        $result = PHPUnit2_TextUI_TestRunner::run($suite);
    }

    /**
     * Sets up the fixture, for example, open a network connection.
     * This method is called before a test is executed.
     *
     * @access protected
     */
    protected function setUp() {
    }

    /**
     * Tears down the fixture, for example, close a network connection.
     * This method is called after a test is executed.
     *
     * @access protected
     */
    protected function tearDown() {
    }

	/**
	 *  @todo Implement testConstruct()
	 */
    public function testConstruct() {
        // Remove the following line when you implement this test.
        throw new PHPUnit2_Framework_IncompleteTestError;
	}

	/**
	 *  @todo Implement testExpiration_date_select()
	 */
    public function testExpiration_date_select() {
        // Remove the following line when you implement this test.
        throw new PHPUnit2_Framework_IncompleteTestError;
	}

	/**
	 *  @todo Implement testDatetime_select_method()
	 */
    public function testDatetime_select_method() {
        // Remove the following line when you implement this test.
        throw new PHPUnit2_Framework_IncompleteTestError;
	}

	/**
	 *  @todo Implement testDatetime_select_function()
	 */
    public function testDatetime_select_function() {
        // Remove the following line when you implement this test.
        throw new PHPUnit2_Framework_IncompleteTestError;
	}

	/**
	 *  @todo Implement testDate_select_method()
	 */
    public function testDate_select_method() {
        // Remove the following line when you implement this test.
        throw new PHPUnit2_Framework_IncompleteTestError;
	}

	/**
	 *  @todo Implement testDate_select_function()
	 */
    public function testDate_select_function() {
        // Remove the following line when you implement this test.
        throw new PHPUnit2_Framework_IncompleteTestError;
	}

	/**
	 *  @todo Implement testSelect_expiration_date_method()
	 */
    public function testSelect_expiration_date_method() {
        // Remove the following line when you implement this test.
        throw new PHPUnit2_Framework_IncompleteTestError;
	}

	/**
	 *  @todo Implement testSelect_expiration_date_function()
	 */
    public function testSelect_expiration_date_function() {
        // Remove the following line when you implement this test.
        throw new PHPUnit2_Framework_IncompleteTestError;
	}

	/**
	 *  @todo Implement testSelect_date_method()
	 */
    public function testSelect_date_method() {
        // Remove the following line when you implement this test.
        throw new PHPUnit2_Framework_IncompleteTestError;
	}

	/**
	 *  @todo Implement testSelect_date_function()
	 */
    public function testSelect_date_function() {
        // Remove the following line when you implement this test.
        throw new PHPUnit2_Framework_IncompleteTestError;
	}

	/**
	 *  @todo Implement testSelect_datetime_method()
	 */
    public function testSelect_datetime_method() {
        // Remove the following line when you implement this test.
        throw new PHPUnit2_Framework_IncompleteTestError;
	}

	/**
	 *  @todo Implement testSelect_datetime_function()
	 */
    public function testSelect_datetime_function() {
        // Remove the following line when you implement this test.
        throw new PHPUnit2_Framework_IncompleteTestError;
	}

	/**
	 *  @todo Implement testSelect_time()
	 */
    public function testSelect_time() {
        // Remove the following line when you implement this test.
        throw new PHPUnit2_Framework_IncompleteTestError;
	}

	/**
	 *  @todo Implement testSelect_second()
	 */
    public function testSelect_second() {
        // Remove the following line when you implement this test.
        throw new PHPUnit2_Framework_IncompleteTestError;
	}

	/**
	 *  @todo Implement testSelect_minute()
	 */
    public function testSelect_minute() {
        // Remove the following line when you implement this test.
        throw new PHPUnit2_Framework_IncompleteTestError;
	}

	/**
	 *  @todo Implement testSelect_hour()
	 */
    public function testSelect_hour() {
        // Remove the following line when you implement this test.
        throw new PHPUnit2_Framework_IncompleteTestError;
	}

	/**
	 *  @todo Implement testSelect_day_method()
	 */
    public function testSelect_day_method() {
        // Remove the following line when you implement this test.
        throw new PHPUnit2_Framework_IncompleteTestError;
	}

	/**
	 *  @todo Implement testSelect_day_function()
	 */
    public function testSelect_day_function() {
        // Remove the following line when you implement this test.
        throw new PHPUnit2_Framework_IncompleteTestError;
	}

	/**
	 *  Test select_month() method
     *
     *  NB: the override of selected month by $_REQUEST only occurs if
     *  the private function check_request_for_value() was previously
     *  called to parse $_REQUEST so we can't test that here.
     *
     *  NB: doesn't test corrects of selection of current month
	 */
    public function testSelect_month_method() {
        $dh = new DateHelper();

        //  Test generation with November selected, default output format
        $this->assertEquals('<select name="month">' . "\n"
                            . '<option value="01">January</option>' . "\n"
                            . '<option value="02">February</option>' . "\n"
                            . '<option value="03">March</option>' . "\n"
                            . '<option value="04">April</option>' . "\n"
                            . '<option value="05">May</option>' . "\n"
                            . '<option value="06">June</option>' . "\n"
                            . '<option value="07">July</option>' . "\n"
                            . '<option value="08">August</option>' . "\n"
                            . '<option value="09">September</option>' . "\n"
                            . '<option value="10">October</option>' . "\n"
                            . '<option value="11" selected="selected">November</option>' . "\n"
                            . '<option value="12">December</option>' . "\n"
                            . '</select>' . "\n",
                            $dh->select_month('11'));

        //  Test generation of month numbers as visible content
        $this->assertEquals('<select name="month">' . "\n"
                            . '<option value="01">1</option>' . "\n"
                            . '<option value="02">2</option>' . "\n"
                            . '<option value="03" selected="selected">3</option>' . "\n"
                            . '<option value="04">4</option>' . "\n"
                            . '<option value="05">5</option>' . "\n"
                            . '<option value="06">6</option>' . "\n"
                            . '<option value="07">7</option>' . "\n"
                            . '<option value="08">8</option>' . "\n"
                            . '<option value="09">9</option>' . "\n"
                            . '<option value="10">10</option>' . "\n"
                            . '<option value="11">11</option>' . "\n"
                            . '<option value="12">12</option>' . "\n"
                            . '</select>' . "\n",
                            $dh->select_month("03",
                                              array('use_month_numbers'=>1)));

        //  Test addition of month numbers to visible content
        $this->assertEquals('<select name="month">' . "\n"
                            . '<option value="01">1 - January</option>' . "\n"
                            . '<option value="02">2 - February</option>' . "\n"
                            . '<option value="03">3 - March</option>' . "\n"
                            . '<option value="04">4 - April</option>' . "\n"
                            . '<option value="05" selected="selected">5 - May</option>' . "\n"
                            . '<option value="06">6 - June</option>' . "\n"
                            . '<option value="07">7 - July</option>' . "\n"
                            . '<option value="08">8 - August</option>' . "\n"
                            . '<option value="09">9 - September</option>' . "\n"
                            . '<option value="10">10 - October</option>' . "\n"
                            . '<option value="11">11 - November</option>' . "\n"
                            . '<option value="12">12 - December</option>' . "\n"
                            . '</select>' . "\n",
                            $dh->select_month("05",
                                              array('add_month_numbers'=>1)));

        // Remove the following line when you implement this test.
        throw new PHPUnit2_Framework_IncompleteTestError;
	}

	/**
	 *  @todo Implement testSelect_month_function()
	 */
    public function testSelect_month_function() {
        // Remove the following line when you implement this test.
        throw new PHPUnit2_Framework_IncompleteTestError;
	}

	/**
	 *  @todo Implement testSelect_year_method()
	 */
    public function testSelect_year_method() {
        // Remove the following line when you implement this test.
        throw new PHPUnit2_Framework_IncompleteTestError;
	}

	/**
	 *  @todo Implement testSelect_year_function()
	 */
    public function testSelect_year_function() {
        // Remove the following line when you implement this test.
        throw new PHPUnit2_Framework_IncompleteTestError;
	}

	/**
	 *  @todo Implement testTo_date_select_tag()
	 */
    public function testTo_date_select_tag() {
        // Remove the following line when you implement this test.
        throw new PHPUnit2_Framework_IncompleteTestError;
	}

	/**
	 *  @todo Implement testTo_datetime_select_tag()
	 */
    public function testTo_datetime_select_tag() {
        // Remove the following line when you implement this test.
        throw new PHPUnit2_Framework_IncompleteTestError;
	}

	/**
	 *  @todo Implement testTo_expiration_date_select_tag_method()
	 */
    public function testTo_expiration_date_select_tag_method() {
        // Remove the following line when you implement this test.
        throw new PHPUnit2_Framework_IncompleteTestError;
	}

	/**
	 *  @todo Implement testTo_expiration_date_select_tag_function()
	 */
    public function testTo_expiration_date_select_tag_function() {
        // Remove the following line when you implement this test.
        throw new PHPUnit2_Framework_IncompleteTestError;
	}

}

// Call DateHelperTest::main() if this source file is executed directly.
if (PHPUnit2_MAIN_METHOD == "DateHelperTest::main") {
    DateHelperTest::main();
}

// -- set Emacs parameters --
// Local variables:
// tab-width: 4
// c-basic-offset: 4
// c-hanging-comment-ender-p: nil
// indent-tabs-mode: nil
// End:
?>
