<?php
/**
 *  File for the FormHelperTest class
 *
 * (PHP 5)
 *
 * @package PHPonTraxTest
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 * @copyright (c) Walter O. Haas 2006
 * @version $Id$
 * @author Walt Haas <haas@xmission.com>
 */

echo "testing FormHelper\n";
require_once 'testenv.php';

// Call FormHelperTest::main() if this source file is executed directly.
if (!defined("PHPUnit2_MAIN_METHOD")) {
    define("PHPUnit2_MAIN_METHOD", "FormHelperTest::main");
}

require_once "PHPUnit2/Framework/TestCase.php";
require_once "PHPUnit2/Framework/TestSuite.php";

// You may remove the following line when all tests have been implemented.
require_once "PHPUnit2/Framework/IncompleteTestError.php";

require_once "action_view/helpers.php";
require_once "action_view/helpers/form_helper.php";

/**
 * Test class for FormHelper.
 * Generated by PHPUnit2_Util_Skeleton on 2006-03-01 at 13:17:32.
 */
class FormHelperTest extends PHPUnit2_Framework_TestCase {
    /**
     * Runs the test methods of this class.
     *
     * @access public
     * @static
     */
    public static function main() {
        require_once "PHPUnit2/TextUI/TestRunner.php";

        $suite  = new PHPUnit2_Framework_TestSuite("FormHelperTest");
        $result = PHPUnit2_TextUI_TestRunner::run($suite);
    }

    /**
     * Sets up the fixture, for example, open a network connection.
     * This method is called before a test is executed.
     *
     * @access protected
     */
    protected function setUp() {
    }

    /**
     * Tears down the fixture, for example, close a network connection.
     * This method is called after a test is executed.
     *
     * @access protected
     */
    protected function tearDown() {
    }

    /**
     *  Test __construct() method
     */
    public function test__construct() {
        $uh = new FormHelper;
        $this->assertTrue(is_object($uh));
        $this->assertEquals('FormHelper', get_class($uh));
    }

    /**
     *  Test add_default_name_and_id() method
     *  @todo Implement this test
     */
    public function testAdd_default_name_and_id_method() {
        // Remove the following line when you implement this test.
        throw new PHPUnit2_Framework_IncompleteTestError;
    }

    /**
     *  Test add_default_name_and_id() function
     *  @todo Implement this test
     */
    public function testAdd_default_name_and_id_function() {
        // Remove the following line when you implement this test.
        throw new PHPUnit2_Framework_IncompleteTestError;
    }

    /**
     *  Test error_wrapping() method
     *  @todo Implement this test
     */
    public function testError_wrapping_method() {
        // Remove the following line when you implement this test.
        throw new PHPUnit2_Framework_IncompleteTestError;
    }

    /**
     *  Test error_wrapping() function
     *  @todo Implement this test
     */
    public function testError_wrapping_function() {
        // Remove the following line when you implement this test.
        throw new PHPUnit2_Framework_IncompleteTestError;
    }

    /**
     *  Test tag_id() method
     *  @todo Implement this test
     */
    public function testTag_id_method() {
        // Remove the following line when you implement this test.
        throw new PHPUnit2_Framework_IncompleteTestError;
    }

    /**
     *  Test tag_id() function
     *  @todo Implement this test
     */
    public function testTag_id_function() {
        // Remove the following line when you implement this test.
        throw new PHPUnit2_Framework_IncompleteTestError;
    }

    /**
     *  Test tag_id_with_index() method
     *  @todo Implement this test
     */
    public function testTag_id_with_index_method() {
        // Remove the following line when you implement this test.
        throw new PHPUnit2_Framework_IncompleteTestError;
    }

    /**
     *  Test tag_id_with_index() function
     *  @todo Implement this test
     */
    public function testTag_id_with_index_function() {
        // Remove the following line when you implement this test.
        throw new PHPUnit2_Framework_IncompleteTestError;
    }

    /**
     *  Test tag_name() method
     *  @todo Implement this test
     */
    public function testTag_name_method() {
        // Remove the following line when you implement this test.
        throw new PHPUnit2_Framework_IncompleteTestError;
    }

    /**
     *  Test tag_name() function
     *  @todo Implement this test
     */
    public function testTag_name_function() {
        // Remove the following line when you implement this test.
        throw new PHPUnit2_Framework_IncompleteTestError;
    }

    /**
     *  Test tag_name_with_index() method
     *  @todo Implement this test
     */
    public function testTag_name_with_index_method() {
        // Remove the following line when you implement this test.
        throw new PHPUnit2_Framework_IncompleteTestError;
    }

    /**
     *  Test tag_name_with_index() function
     *  @todo Implement this test
     */
    public function testTag_name_with_index_function() {
        // Remove the following line when you implement this test.
        throw new PHPUnit2_Framework_IncompleteTestError;
    }

    /**
     *  Test to_boolean_select_tag() method
     *  @todo Implement this test
     */
    public function testTo_boolean_select_tag_method() {
        // Remove the following line when you implement this test.
        throw new PHPUnit2_Framework_IncompleteTestError;
    }

    /**
     *  Test to_boolean_select_tag() function
     *  @todo Implement this test
     */
    public function testTo_boolean_select_tag_function() {
        // Remove the following line when you implement this test.
        throw new PHPUnit2_Framework_IncompleteTestError;
    }

    /**
     *  Test to_check_box_tag() method
     *  @todo Implement this test
     */
    public function testTo_check_box_tag_method() {
        // Remove the following line when you implement this test.
        throw new PHPUnit2_Framework_IncompleteTestError;
    }

    /**
     *  Test to_check_box_tag() function
     *  @todo Implement this test
     */
    public function testTo_check_box_tag_function() {
        // Remove the following line when you implement this test.
        throw new PHPUnit2_Framework_IncompleteTestError;
    }

    /**
     *  Test to_input_field_tag() method
     *  @todo Implement this test
     */
    public function testTo_input_field_tag_method() {
        // Remove the following line when you implement this test.
        throw new PHPUnit2_Framework_IncompleteTestError;
    }

    /**
     *  Test to_input_field_tag() function
     *  @todo Implement this test
     */
    public function testTo_input_field_tag_function() {
        // Remove the following line when you implement this test.
        throw new PHPUnit2_Framework_IncompleteTestError;
    }

    /**
     *  Test to_radio_button_tag() method
     *  @todo Implement this test
     */
    public function testTo_radio_button_tag_method() {
        // Remove the following line when you implement this test.
        throw new PHPUnit2_Framework_IncompleteTestError;
    }

    /**
     *  Test to_radio_button_tag() function
     *  @todo Implement this test
     */
    public function testTo_radio_button_tag_function() {
        // Remove the following line when you implement this test.
        throw new PHPUnit2_Framework_IncompleteTestError;
    }

    /**
     *  Test to_text_area_tag() method
     *  @todo Implement this test
     */
    public function testTo_text_area_tag_method() {
        // Remove the following line when you implement this test.
        throw new PHPUnit2_Framework_IncompleteTestError;
    }

    /**
     *  Test to_text_area_tag() function
     *  @todo Implement this test
     */
    public function testTo_text_area_tag_function() {
        // Remove the following line when you implement this test.
        throw new PHPUnit2_Framework_IncompleteTestError;
    }


}

// Call FormHelperTest::main() if this source file is executed directly.
if (PHPUnit2_MAIN_METHOD == "FormHelperTest::main") {
    FormHelperTest::main();
}

// -- set Emacs parameters --
// Local variables:
// tab-width: 4
// c-basic-offset: 4
// c-hanging-comment-ender-p: nil
// indent-tabs-mode: nil
// End:
?>
