<refentry id="{@id}">
 <refnamediv>
  <refname>TraxError</refname>
  <refpurpose>Error exception thrown by Trax modules</refpurpose>
 </refnamediv>
 <refsynopsisdiv>
  <author>
   Walt Haas
   <authorblurb>
    {@link mailto:haas@xmission.com haas@xmission.com}
   </authorblurb>
  </author>
 </refsynopsisdiv>
 {@toc}
 <refsect1 id="{@id intro}">
  <title>Introduction</title>
  <para>{@link TraxError} extends
   {@link http://www.php.net/exceptions Exception} by adding a few
   fields of interest to Trax modules.
  </para>
 </refsect1>
</refentry>
