<refentry id="{@id}" revision="$Id$">
 <refnamediv>
  <refname>ActiveRecordError</refname>
  <refpurpose>Error exception thrown by ActiveRecord</refpurpose>
 </refnamediv>
 <refsynopsisdiv>
  <author>
   Walt Haas
   <authorblurb>
    {@link mailto:haas@xmission.com haas@xmission.com}
   </authorblurb>
  </author>
 </refsynopsisdiv>
 {@toc}
 <refsect1 id="{@id intro}">
  <title>Introduction</title>
  <para><important>ActiveRecordError</important> extends
   {@tutorial PHPonTrax/TraxError.cls} with no changes.</para>
 </refsect1>
</refentry>
