<refentry id="{@id}" revision="$Id$">
 <refnamediv>
  <refname>Session</refname>
  <refpurpose>@todo Session tutorial</refpurpose>
 </refnamediv>
 <refsynopsisdiv>
  <author>
   Walt Haas
   <authorblurb>
    {@link mailto:haas@xmission.com haas@xmission.com}
   </authorblurb>
  </author>
 </refsynopsisdiv>
 {@toc}
 <refsect1 id="{@id intro}">
  <title>Introduction</title>
 </refsect1>
</refentry>
